# SConscript for cache subdirectory

# Import envrionment
Import('env')

# Now get list of .cpp files
src_files = Glob('*.cpp')

core_model_dirs = ['default_core', 'atom-core']

core_objs = []
for core_model in core_model_dirs:
    core_objs += SConscript('%s/SConscript' % core_model)

objs = env.Object(src_files)

objs += core_objs

Return('objs')
