# SConscript for cache subdirectory

# Import envrionment
Import('env')

# Now get list of .cpp files
src_files = Glob('*.cpp')

objs = env.Object(src_files)

# specific list of objects for dstbuild
dst_objs = env.Object(Split("superstl.cpp statelist.cpp"))

ret_objs = [objs, dst_objs]
Return('ret_objs')
