# SConscript for tests subdirectory

# Import envrionment
Import('env')

# Now get list of .cpp files
src_files = Glob('*.cpp')
src_files.remove(File('atomcore-test.cpp'))

atomcore_o = env.Object('atomcore-test.cpp')
env.Depends(atomcore_o, '../core/atom-core/atomcore.cpp')

objs = env.Object(src_files)

ret_objs = objs + [atomcore_o]
Return('ret_objs')
